/**
 * #1216 — generate-ssid-patterns 헬퍼 단위 테스트.
 * main()은 fs 부수효과라 헬퍼만 검증.
 */
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {
  CARRIER_PATTERNS,
  normalizeEnglishToken,
  buildAutoPatterns,
  buildEntries,
  buildOutput,
  readJson,
  writeJson,
  main,
} = require('../generate-ssid-patterns');

const STATIONS_FIXTURE = [
  { id: '1-001', name: '소요산', nameEn: 'Soyosan' },
  { id: '2-001', name: '강남', nameEn: 'Gangnam' },
  { id: '2-002', name: '서울대입구', nameEn: 'Seoul Nat Univ' },
  { id: '3-001', name: '경복궁', nameEn: '' },
  { id: '4-001', name: '의정부', nameEn: 'Uijeongbu' },
  // 환승역 중복(같은 한글명, 다른 line) — 하나의 entry만 생성되어야 함
  { id: '7-001', name: '강남', nameEn: 'Gangnam' },
];

const MANUAL_FIXTURE = [
  { stationName: '강남', patterns: ['^T_subway_강남', 'Gangnam_Station'] },
];

describe('CARRIER_PATTERNS', () => {
  it('SKT/KT/LGU+ 3종 통신사 prefix를 포함한다', () => {
    const ids = CARRIER_PATTERNS.map((c) => c.id);
    expect(ids).toEqual(['skt', 'kt', 'lgu']);
  });

  it('통신사 prefix 정규식 시작 anchor 또는 escape 포함', () => {
    expect(CARRIER_PATTERNS[0].prefix).toBe('^T_subway_');
    expect(CARRIER_PATTERNS[1].prefix).toBe('^Olleh_Subway_');
    expect(CARRIER_PATTERNS[2].prefix).toBe('U\\+Subway_');
  });

  it('Object.freeze로 봉인된다', () => {
    expect(Object.isFrozen(CARRIER_PATTERNS)).toBe(true);
  });
});

describe('normalizeEnglishToken', () => {
  it.each([
    ['Soyosan', 'Soyosan'],
    ['Seoul Nat Univ', 'Seoul_Nat_Univ'],
    ['  Hongik  Univ  ', 'Hongik_Univ'],
    ['Dongdaemun-History', 'DongdaemunHistory'],
    ['Express Bus Terminal!', 'Express_Bus_Terminal'],
  ])('"%s" → "%s"', (input, expected) => {
    expect(normalizeEnglishToken(input)).toBe(expected);
  });

  it.each([['', null], ['   ', null], ['!!!', null]])(
    '빈/특수문자만 입력 → null ("%s")',
    (input, expected) => {
      expect(normalizeEnglishToken(input)).toBe(expected);
    },
  );

  it.each([[null], [undefined], [42], [{}]])('비문자열 입력 → null (%p)', (input) => {
    expect(normalizeEnglishToken(input)).toBeNull();
  });
});

describe('buildAutoPatterns', () => {
  it('영문 토큰 있으면 통신사 3 + 영문 1 = 4개', () => {
    const patterns = buildAutoPatterns('강남', 'Gangnam');
    expect(patterns).toHaveLength(4);
    expect(patterns).toContain('^T_subway_강남');
    expect(patterns).toContain('^Olleh_Subway_강남');
    expect(patterns).toContain('U\\+Subway_강남');
    expect(patterns).toContain('Gangnam');
  });

  it('영문 토큰 없으면 통신사 3개만', () => {
    const patterns = buildAutoPatterns('경복궁', '');
    expect(patterns).toHaveLength(3);
    expect(patterns.every((p) => p.includes('경복궁'))).toBe(true);
  });

  it('영문 nameEn null이면 통신사 3개만', () => {
    const patterns = buildAutoPatterns('경복궁', null);
    expect(patterns).toHaveLength(3);
  });
});

describe('buildEntries', () => {
  it('manual entry는 보존되고 미등록 역은 auto 생성', () => {
    const result = buildEntries(STATIONS_FIXTURE, MANUAL_FIXTURE);
    expect(result.manualEntriesCount).toBe(1);
    // unique 한글명: 소요산/강남/서울대입구/경복궁/의정부 = 5개. 강남은 manual로 등록.
    expect(result.autoGeneratedCount).toBe(4);
    expect(result.entries[0]).toEqual(MANUAL_FIXTURE[0]);
  });

  it('환승역 중복 한글명은 하나의 auto entry만 만든다', () => {
    const stations = [
      { id: '2-001', name: '잠실', nameEn: 'Jamsil' },
      { id: '8-001', name: '잠실', nameEn: 'Jamsil' },
    ];
    const result = buildEntries(stations, []);
    expect(result.autoGeneratedCount).toBe(1);
    expect(result.entries).toHaveLength(1);
  });

  it('빈/undefined 역명은 무시한다', () => {
    const stations = [
      { id: 'x-1', name: '', nameEn: 'X' },
      { id: 'x-2', nameEn: 'Y' },
      { id: 'x-3', name: '용산', nameEn: 'Yongsan' },
    ];
    const result = buildEntries(stations, []);
    expect(result.autoGeneratedCount).toBe(1);
    expect(result.entries[0].stationName).toBe('용산');
  });

  it('auto entries는 한글명 기준 정렬된다 (결정적 diff)', () => {
    const stations = [
      { id: '1', name: '홍대입구', nameEn: 'Hongik' },
      { id: '2', name: '강남', nameEn: 'Gangnam' },
      { id: '3', name: '서울역', nameEn: 'Seoul' },
    ];
    const result = buildEntries(stations, []);
    const autoNames = result.entries.map((e) => e.stationName);
    expect(autoNames).toEqual(['강남', '서울역', '홍대입구']);
  });
});

describe('buildOutput', () => {
  const NOW = '2026-06-12T00:00:00.000Z';

  it('_meta에 generatedAt + count + strategy를 갱신한다', () => {
    const existing = { _meta: { description: 'orig' }, entries: MANUAL_FIXTURE };
    const out = buildOutput(STATIONS_FIXTURE, existing, NOW);
    expect(out._meta.generatedAt).toBe(NOW);
    expect(out._meta.patternStrategy).toBe('carrier-default-with-station-name');
    expect(out._meta.manualEntriesCount).toBe(1);
    expect(out._meta.autoGeneratedCount).toBe(4);
    expect(out._meta.totalEntries).toBe(5);
    expect(out._meta.description).toBe('orig'); // 기존 description 보존
  });

  it('$schema는 기존 값 보존, 없으면 default', () => {
    const withSchema = { $schema: './x.schema', entries: [] };
    expect(buildOutput([], withSchema, NOW).$schema).toBe('./x.schema');
    const noSchema = { entries: [] };
    expect(buildOutput([], noSchema, NOW).$schema).toBe('./subwayWifiSsidMap.schema');
  });

  it('_meta 없는 입력도 처리한다', () => {
    const out = buildOutput([], { entries: [] }, NOW);
    expect(out._meta.totalEntries).toBe(0);
  });

  it('entries가 array 아니면 빈 배열로 처리', () => {
    const out = buildOutput(STATIONS_FIXTURE, {}, NOW);
    expect(out._meta.manualEntriesCount).toBe(0);
    // unique 한글명 5개 모두 auto
    expect(out._meta.autoGeneratedCount).toBe(5);
  });
});

describe('실제 데이터 무결성', () => {
  // outer scope helpers: 실제 JSON에 대해 회귀 점검 (스크립트 실행 후 상태 검증)
  const actualMap = require('../../src/data/subwayWifiSsidMap.json');
  const actualStations = require('../../src/data/stations.json');

  it('19개 manual entry가 보존된다 (수동 등록 패턴 회귀 방지)', () => {
    const MANUAL_NAMES = [
      '용마산',
      '중곡',
      '군자(능동)',
      '강남',
      '서울역',
      '시청',
      '종로3가',
      '왕십리',
      '건대입구',
      '성수',
      '잠실(송파구청)',
      '사당',
      '총신대입구(이수)',
      '고속터미널',
      '신도림',
      '홍대입구',
      '교대(법원.검찰청)',
      '동대문역사문화공원',
      '공덕',
    ];
    const entryNames = actualMap.entries.map((e) => e.stationName);
    for (const name of MANUAL_NAMES) {
      expect(entryNames).toContain(name);
    }
  });

  it('_meta에 필수 필드가 모두 존재한다', () => {
    expect(actualMap._meta.generatedAt).toEqual(expect.any(String));
    expect(actualMap._meta.patternStrategy).toBe('carrier-default-with-station-name');
    expect(actualMap._meta.manualEntriesCount).toEqual(expect.any(Number));
    expect(actualMap._meta.autoGeneratedCount).toEqual(expect.any(Number));
    expect(actualMap._meta.totalEntries).toBe(actualMap.entries.length);
  });

  it('총 entry 수 = unique 한글명 수 (중복 없음)', () => {
    const uniqNames = new Set(actualStations.map((s) => s.name));
    expect(actualMap.entries.length).toBe(uniqNames.size);
  });

  it('핵심 환승역 샘플의 통신사 패턴이 존재한다', () => {
    const SAMPLE_NAMES = ['시청', '강남', '잠실(송파구청)', '왕십리', '홍대입구'];
    for (const name of SAMPLE_NAMES) {
      const entry = actualMap.entries.find((e) => e.stationName === name);
      expect(entry).toBeDefined();
      expect(entry.patterns.some((p) => p.startsWith('^T_subway_'))).toBe(true);
    }
  });

  it('JSON 파일 사이즈 200KB 이하', () => {
    const filePath = path.join(__dirname, '..', '..', 'src', 'data', 'subwayWifiSsidMap.json');
    const { size } = fs.statSync(filePath);
    expect(size).toBeLessThan(200 * 1024);
  });
});

describe('readJson / writeJson', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ssid-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('readJson은 디스크에서 JSON을 파싱한다', () => {
    const filePath = path.join(tmpDir, 'sample.json');
    fs.writeFileSync(filePath, JSON.stringify({ a: 1 }));
    expect(readJson(filePath)).toEqual({ a: 1 });
  });

  it('writeJson은 pretty-printed JSON + trailing newline으로 기록한다', () => {
    const filePath = path.join(tmpDir, 'out.json');
    writeJson(filePath, { x: [1, 2] });
    const raw = fs.readFileSync(filePath, 'utf8');
    expect(raw).toBe('{\n  "x": [\n    1,\n    2\n  ]\n}\n');
  });
});

describe('main', () => {
  it('실제 데이터로 결정적으로 재생성된다 (idempotent)', () => {
    const SSID_PATH = path.join(__dirname, '..', '..', 'src', 'data', 'subwayWifiSsidMap.json');
    const before = fs.readFileSync(SSID_PATH, 'utf8');
    const logs = [];
    const logger = { log: (msg) => logs.push(msg) };
    const result = main({ logger });
    expect(result._meta.totalEntries).toBe(result.entries.length);
    expect(logs).toHaveLength(1);
    expect(logs[0]).toMatch(/manual=\d+ auto=\d+ total=\d+/);
    // 복원: 테스트 후 동일 generatedAt 차이만 있으므로 다시 before로 되돌리지 않아도
    // 다음 main() 호출이 동일 결과를 만든다. 단, 파일 상태가 변할 수 있으므로
    // entries 길이/구조만 검증.
    fs.writeFileSync(SSID_PATH, before, 'utf8');
  });

  it('인자 없이 호출 시 console.log를 사용한다 (default branch)', () => {
    const SSID_PATH = path.join(__dirname, '..', '..', 'src', 'data', 'subwayWifiSsidMap.json');
    const before = fs.readFileSync(SSID_PATH, 'utf8');
    const spy = jest.spyOn(console, 'log').mockImplementation(() => {});
    main();
    expect(spy).toHaveBeenCalledTimes(1);
    spy.mockRestore();
    fs.writeFileSync(SSID_PATH, before, 'utf8');
  });
});
